name: Update ICS File

on:
  schedule:
    # This cron job runs every hour
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update_ics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: pip install pytz  # Add any other dependencies your script may need
    
    - name: Generate and push ICS file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by Actions, no need to set manually
      run: python calendar_logger.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update ICS file" || echo "No changes to commit"
        git push
