name: Update ICS File

on:
  schedule:
    # This cron job runs at 00:00 every day. Adjust as needed.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_ics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: pip install pytz  # Or any other dependencies your script may need
    
    - name: Generate and push ICS file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by Actions, no need to set manually
      run: python calendar_logger.py
